import { SoundControls } from './sound-controls.js';
const $=s=>document.querySelector(s);
export const formatTime=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
export class UI{
 constructor(audio){this.audio=audio;this.toastTimer=null;this.modalOpened=false;this.touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>1;if(this.touch)document.body.classList.add('touch-device');this.map=$('#minimap');this.ctx=this.map.getContext('2d');this.frame=0;}
 bind(game){this.game=game;this.soundControls=new SoundControls(this.audio,game);const focusButton=$('#focus-mode');const syncFocus=()=>{focusButton.setAttribute('aria-pressed',String(game.world.dof.enabled));focusButton.setAttribute('aria-label',game.world.dof.enabled?'关闭景深':'开启景深');};focusButton.onclick=()=>{game.world.dof.enabled=!game.world.dof.enabled;localStorage.setItem('wanbu-dof',game.world.dof.enabled?'on':'off');syncFocus();};syncFocus();if(this.touch){for(const [id,label]of[['touch-dash','冲刺'],['touch-echo','回声'],['touch-interact','互动']]){let el=document.querySelector('#'+id);el.innerHTML='<span>'+el.innerHTML+'</span><small>'+label+'</small>';}}$('#help').onclick=()=>this.showHelp();$('#pause').onclick=()=>this.pause();$('#modal-close').onclick=()=>this.close();$('#dash-button').onclick=()=>game.dash();$('#echo-button').onclick=()=>game.echo();$('#interact-button').onclick=()=>game.interact();$('#touch-dash').onpointerdown=e=>{e.preventDefault();game.dash()};$('#touch-echo').onpointerdown=e=>{e.preventDefault();game.echo()};$('#touch-interact').onpointerdown=e=>{e.preventDefault();game.interact()};$('.brand').onclick=()=>{if(game.active)game.save();};
  const joystick=$('#joystick'),knob=joystick.querySelector('i');let pointer=null;const move=e=>{if(pointer!==e.pointerId)return;let r=joystick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,d=Math.hypot(dx,dy),m=38;if(d>m){dx*=m/d;dy*=m/d}knob.style.transform=`translate(${dx}px,${dy}px)`;game.joy.set(dx/m,dy/m)};joystick.onpointerdown=e=>{pointer=e.pointerId;joystick.setPointerCapture(pointer);move(e)};joystick.onpointermove=move;const end=e=>{if(pointer===e.pointerId){pointer=null;knob.style.transform='';game.joy.set(0,0)}};joystick.onpointerup=end;joystick.onpointercancel=end;
  this.mapBackground=document.createElement('canvas');this.mapBackground.width=240;this.mapBackground.height=166;let c=this.mapBackground.getContext('2d');c.fillStyle='#0e242c';c.fillRect(0,0,240,166);const n=game.world.nav;for(let sy=16;sy<=77;sy+=.5)for(let sx=305;sx<=367;sx+=.5){let i=Math.round((sx-n.x)/n.step),j=Math.round((sy-n.y)/n.step);const h=n.levels[1][j][i];if(h===null)continue;let p=this.mapPoint({x:sx-300,z:60-sy});c.fillStyle=h>5.4?'#355855':h>1?'#738c76':'#1d3940';c.fillRect(p.x,p.y,2.1,1.4);}c.strokeStyle='#78a49922';for(let x=0;x<240;x+=30){c.beginPath();c.moveTo(x,0);c.lineTo(x,166);c.stroke()}for(let y=0;y<166;y+=28){c.beginPath();c.moveTo(0,y);c.lineTo(240,y);c.stroke()}
 }
 start(){$('body').classList.add('playing');$('#hud').classList.remove('hidden');if(this.touch)$('#touch').classList.remove('hidden');this.close();}
 quest(){const g=this.game;const chapters=[['01 · 万步起点','追随第一道足迹','沿着金色能量前进，收集三枚能量，唤醒联动能力。'],['02 · 连廊接力',g.step===0?'沿楼梯，走向二层':'与刚才的自己协作',g.step===0?'登上入口楼梯，前往青色 A 感应点。':'在 A 点按 E 记录约 3 秒，再按 E 回放。前往 B 点，与回声同时停留。'],['03 · 空中花园',g.gateIndex<3?'把握光门的节奏':'把创新带向世界',g.gateIndex<3?'按顺序穿过三道光门。青色时通过，也可以用冲刺穿过橙色光门。':'三道光门已点亮。前往花园光环，按 F 收集创新成果。'],['04 · 全球联动','让每一步，连接世界','带着创新成果返回二层连廊，在全球节点旁按 F，完成万步联动。'],['旅程完成','永不止步','你已连接整个园区。继续探索，寻找散落的园区记忆。']];const data=chapters[g.chapter];$('#chapter-tag').textContent=data[0];$('#quest-title').textContent=data[1];$('#quest-description').textContent=this.inputText(data[2]);$('#chapter-count').textContent=`0${Math.min(4,g.chapter+1)} / 04`;let count=g.chapter===0?g.step:g.chapter===2?g.gateIndex:0;$('#quest-progress').innerHTML=g.chapter===0||g.chapter===2?[0,1,2].map(i=>`<span class="${count>i?'done':''}">${g.chapter===0?'能量':'光门'} 0${i+1}</span>`).join(''):g.chapter===1?'<span>A 足迹记录</span><span>B 同步联动</span>':'';$('#echo-button').classList.toggle('locked',!g.echoUnlocked);}
 update(){const g=this.game;$('#score').textContent=String(g.score).padStart(4,'0');$('#score-fill').style.width=g.score/100+'%';$('#timer').textContent=formatTime(g.time);$('#dash-status').textContent=g.dashCooldown>0?g.dashCooldown.toFixed(1)+' 秒':'已就绪';$('#dash-button').classList.toggle('cooling',g.dashCooldown>0);$('#dash-button').setAttribute('aria-label',g.dashCooldown>0?'冲刺冷却 '+g.dashCooldown.toFixed(1)+' 秒':'冲刺，已就绪');$('#dash-fill').style.width=(1-g.dashCooldown/1.65)*100+'%';$('#echo-status').textContent=!g.echoUnlocked?'等待解锁':g.recording?'再次按 E 回放':g.echoPlaying?'回声运行中':'按 E 开始记录';$('#echo-button').classList.toggle('recording',g.recording);$('#echo-fill').style.width=g.recording?g.recordTime/6*100+'%':g.echoPlaying?Math.max(0,1-g.echoTime/(g.echoDuration+4))*100+'%':g.echoUnlocked?'100%':'0%';$('#record-hint').classList.toggle('hidden',!g.recording);$('#record-time').textContent=`${g.recordTime.toFixed(1)} / 6.0 秒`;$('#floor-label').textContent=g.position.y>3?'2F':'1F';$('#location').textContent=g.position.y<3?'入口广场':g.position.x<32?'空中花园':'空中连廊';$('#collect-count').textContent=`探索 ${g.collected.size} / 12`;
  let prompt='';if(g.chapter===1&&g.step===1){if(g.near(g.points.a,2.3)&&!g.recording&&!g.echoPlaying)prompt='E 开始记录 · 在 A 点停留约 3 秒';if(g.recording)prompt=g.recordTime>2.8?'再次按 E 回放，然后前往 B 点':'站在 A 点，让回声记住你';if(g.echoPlaying&&!g.near(g.points.b,1.4))prompt='现在前往 B 点 · 可按 Shift 冲刺';if(g.padCharge>0)prompt=`正在同步 ${Math.round(g.padCharge/1.2*100)}%`;}
  if(g.chapter===2&&g.gateIndex===3&&g.near(g.points.garden,3))prompt='F 收集创新成果';if(g.chapter===3&&g.near(g.points.global,4))prompt='F 连接全球 · 完成万步联动';if(!prompt&&g.world.pond.contains(g.position,1.25))prompt='水纹庭 · 点击水面，或涉水留下涟漪';if(!prompt&&g.nearbyNPC()>=0)prompt='F 交谈 · 园区伙伴';$('#prompt').textContent=this.inputText(prompt);$('#prompt').classList.toggle('hidden',!prompt);if(++this.frame%3===0)this.drawMap();
 }
 inputText(s){return this.touch?s.replace(/Shift/g,'冲刺').replace(/ E /g,' 回声 ').replace(/E /g,'回声 ').replace(/ F /g,' 互动 ').replace(/^F /,'互动 · '):s;}
 mapPoint(p){return{x:(p.x+300-305)/62*220+10,y:(77-(60-p.z))/61*146+10}}
 drawMap(){const c=this.ctx,g=this.game;c.clearRect(0,0,240,166);c.drawImage(this.mapBackground,0,0);if(g.guidePath.length){c.strokeStyle='#a4f8dd88';c.setLineDash([2,3]);c.beginPath();for(let i=0;i<g.guidePath.length;i++){let p=this.mapPoint(g.guidePath[i]);i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y)}c.stroke();c.setLineDash([]);}const target=g.target();if(target){let p=this.mapPoint(target);c.strokeStyle='#f3d09b';c.lineWidth=1.5;c.beginPath();c.arc(p.x,p.y,5,0,Math.PI*2);c.stroke();}for(let s of g.extras){if(s.collected)continue;let p=this.mapPoint(s.base);c.fillStyle='#a5e5cf77';c.fillRect(p.x-1,p.y-1,2,2);}if(g.echoPlaying){let p=this.mapPoint(g.ghost.root.position);c.fillStyle='#72dce8';c.beginPath();c.arc(p.x,p.y,3,0,Math.PI*2);c.fill();}let p=this.mapPoint(g.position);c.fillStyle='#e5fff1';c.shadowColor='#b6ffe6';c.shadowBlur=9;c.beginPath();c.arc(p.x,p.y,3.4,0,Math.PI*2);c.fill();c.shadowBlur=0;}
 toast(text,score=''){clearTimeout(this.toastTimer);$('#toast').replaceChildren();if(score){let strong=document.createElement('strong');strong.textContent=score;$('#toast').append(strong);}$('#toast').append(document.createTextNode(text));$('#toast').classList.remove('hidden');this.toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),3400);}
 modal(html){this.soundControls.close(false);this.game.paused=true;this.game.keys.clear();this.game.joy.set(0,0);this.modalOpened=true;$('#modal-content').innerHTML=html;$('#modal').classList.remove('hidden');$('#modal-close').focus();}
 close(){this.modalOpened=false;$('#modal').classList.add('hidden');if(this.game){this.game.paused=false;this.game.keys.clear();if(this.game.active)this.game.world.canvas.focus();}}
 pause(force=false){if(!this.game.active)return;if(this.modalOpened&&!force){this.close();return;}this.modal('<h2 id="modal-title">旅程暂停</h2><p>歇一歇，让下一步更有力量。<br>你的进度已保存在这台设备上。</p><button id="resume-game" class="primary">继续旅程 <span>↗</span></button><button id="restart-game" class="text-button dark-link">重新开始</button>');$('#resume-game').onclick=()=>this.close();$('#restart-game').onclick=()=>{localStorage.removeItem('wanbu-save-v1');location.reload()};this.game.save();}
 showHelp(mode='general'){this.modal(`<h2 id="modal-title">${mode==='echo'?'足迹，也能协作':'和小步一起出发'}</h2><p>${mode==='echo'?'按 E 开始记录你的行动，再按 E，让回声重复这段路线。回声会在终点停留 4 秒。试着让它留在 A 点，自己跑向 B 点。':'沿光点探索上海安踏中心。完成连廊接力、花园光门和全球联动，积累 10000 联动值。'}</p><ul class="controls-list"><li><b>移动</b><span><kbd>WASD</kbd><kbd>方向键</kbd> / 点击地面</span></li><li><b>短距离冲刺</b><span><kbd>Shift</kbd> 或 <kbd>空格</kbd></span></li><li><b>记录 / 释放足迹回声</b><span><kbd>E</kbd></span></li><li><b>与节点互动</b><span><kbd>F</kbd></span></li><li><b>暂停</b><span><kbd>Esc</kbd></span></li></ul><p class="facts">五栋建筑，以连廊与中庭相互连接。<br>“健康工作，万步联动”来自上海安踏中心的设计理念。足迹回声与光门是本游戏的数字挑战。入口水纹庭是游戏化景观，点击或涉水会产生实时涟漪。右上角 ◎ 可切换景深，扬声器可调节音乐和音效。</p><button id="help-done" class="primary">明白了 <span>↗</span></button>`);$('#help-done').onclick=()=>this.close();}
 finish(){const g=this.game;const medal=g.time<180&&g.retries===0?'金色足迹':g.time<360?'银色足迹':'联动探索者';this.modal(`<h2 id="modal-title">每一步，都有回响。</h2><p>你和小步完成了上海安踏中心的联动旅程。</p><div class="finish-score">10000</div><div class="finish-sub">${medal} · 万步联动达成</div><div class="finish-stats"><div><strong>${formatTime(g.time)}</strong>旅程用时</div><div><strong>${g.collected.size} / 12</strong>园区记忆</div><div><strong>${g.retries}</strong>光门重试</div></div><p class="facts">以晋江为根脉，与厦门、上海相互连接。<br>让运动、创新与多品牌协作，从中国走向世界。</p><button id="explore-more" class="primary">继续探索 <span>↗</span></button><button id="replay" class="text-button dark-link">再跑一次，挑战更好成绩 →</button>`);$('#explore-more').onclick=()=>this.close();$('#replay').onclick=()=>{localStorage.setItem('wanbu-autostart','1');location.reload()};}
}
