// A small connected world: mobility opens topology, rather than a chapter counter.
const p=(id,left,right,y=0)=>({id,left,right,y});
export const ROOMS={
 hub:{name:'大堂',subtitle:'万步联动 · 10K Connectivity',theme:'atrium',width:32,map:[1,1],
  platforms:[p('floor',-2,34),p('balcony',10,18,2.3)],
  exits:{left:{room:'lab',x:29,y:0},right:{room:'atrium',x:2,y:0}},
  items:[{id:'energy-route',type:'route',x:11,y:2.3,label:'前往国际化健身中心',room:'energy',toX:3,toY:0,requires:'dash'},{id:'hub-bench',type:'bench',x:8,y:0,label:'休息并存档'},{id:'hub-lift',type:'shortcut-return',x:15,y:2.3,label:'乘捷径升降台'},{id:'hub-note',type:'note',x:4,y:0,label:'阅读：万步联动'}],
  gate:{x:26,y:0},enemies:[],chips:[{id:'h1',x:12,y:3.35}],
  fact:'从大堂出发，循着「万步联动」的动线探索园区。健步道、水平连廊与垂直中庭相互串联，每一条回路都能带你抵达新的空间。'},
 lab:{name:'水平连廊',subtitle:'万步联动 · 连接办公与运动',theme:'lab',width:32,map:[0,1],
  relay:{flag:'relayOpen',title:'连廊双点同步',pads:[{x:26.7,y:0},{x:13,y:2}],hold:1.1},
  platforms:[p('l',-2,9),p('m',12,22),p('r',25,34),p('p1',7,14,2),p('p2',18,24,2.2),p('archive-ledge',1,6,5)],
  exits:{left:{room:'core',x:29,y:0},right:{room:'hub',x:2,y:0}},
  items:[{id:'archive-route',type:'route',x:3,y:5,label:'前往1楼电梯厅',room:'archive',toX:3,toY:0,requires:'doubleJump'},{id:'lab-note',type:'note',x:28,y:0,label:'阅读：万步联动'},{id:'echo-route',type:'echo-route',x:17,y:0,label:'查看花园连廊入口'}],
  enemies:[{id:'lab-drone',x:17,y:0,min:14,max:21,hp:2}],chips:[{id:'l1',x:10,y:3},{id:'l2',x:21,y:3.2}],
  fact:'多层水平连廊串联各栋建筑，让办公与运动在日常步行中相遇。5F会议中心的科技密室藏着回声项圈。带着它回来，与全息伙伴同步两个感应点，开启空中花园新路线。'},
 core:{name:'5F会议中心',subtitle:'数字大屏 · 数据驱动的开放姿态',theme:'lab',width:32,map:[0,2],
  platforms:[p('floor',-2,34),p('p1',20,28,1.9),p('p2',13,20,3.8),p('p3',4,13,5.7)],
  exits:{right:{room:'lab',x:2,y:0}},
  items:[{id:'dash-module',type:'ability',x:7,y:5.7,label:'取得脉冲冲刺'},{id:'tech-room',type:'tech-room',x:11.5,y:5.7,label:'进入 ANTA 科技密室'}],
  enemies:[{id:'core-drone',x:10,y:5.7,min:8.5,max:12,hp:3}],chips:[{id:'c1',x:24,y:2.9},{id:'c2',x:16,y:4.8}],
  fact:'多层通高的中庭、巨幅数字展示屏与环形走廊，让会议中心兼具品牌展示、员工交流与活动发布的功能。登上展示台完成训练，取得脉冲冲刺，再返回大堂穿过光幕。'},
 atrium:{name:'垂直中庭',subtitle:'连廊向上 · 打开新的高度',theme:'atrium',width:32,map:[2,1],
  platforms:[p('floor',-2,9),p('p1',11,17,2),p('p2',20,26,4),p('top',25,34,6)],
  exits:{left:{room:'hub',x:29,y:0}},
  items:[{id:'garden-lift',type:'lift',x:29,y:6,label:'前往空中花园'}],
  enemies:[{id:'atrium-drone',x:14,y:2,min:12.5,max:16,hp:2}],chips:[{id:'a1',x:23,y:5}],
  fact:'水平连廊与垂直中庭共同组成健康办公的运动网络。把跳跃、空中冲刺和落点判断组合起来，便能抵达更高一层。'},
 garden:{name:'空中花园',subtitle:'健康工作 · 自然中的休息',theme:'garden',width:32,map:[2,0],
  relay:{flag:'gardenOnline',title:'花园循环供能',pads:[{x:15,y:2},{x:28,y:6}],hold:1.1},
  platforms:[p('floor',-2,34),p('p1',12,18,2),p('p2',19,25,4),p('p3',24,32,6)],
  exits:{right:{room:'arena',x:3,y:0}},
  items:[{id:'gallery-route',type:'route',x:28,y:6,label:'前往员工办公区',room:'gallery',toX:3,toY:0},{id:'shortcut',type:'shortcut',x:3,y:0,label:'查看大堂捷径'},{id:'garden-bench',type:'bench',x:8,y:0,label:'休息并存档'},{id:'atrium-lift',type:'back-lift',x:12,y:0,label:'返回垂直中庭'},{id:'garden-note',type:'note',x:18,y:0,label:'阅读：绿色办公'},{id:'echo-back',type:'echo-back',x:22,y:0,label:'沿新连廊返回水平连廊'}],
  enemies:[],chips:[{id:'g1',x:21,y:5},{id:'g2',x:15,y:3}],heart:{x:28,y:7},
  fact:'立体庭院与空中花园，让健康工作延伸到自然之中。在长椅休息可以恢复体力，沿上层路线探索，还能发现永久体力奖励与通往员工办公区的入口。'},
 energy:{name:'国际化健身中心',subtitle:'健康工作 · 在运动中蓄积能量',theme:'energy',width:32,map:[1,2],trial:'energyTrial',
  platforms:[p('floor',-2,34),p('l',5,11,2.2),p('r',21,27,2.2)],exits:{},
  items:[{id:'energy-back',type:'route',x:3,y:0,label:'返回大堂',room:'hub',toX:11,toY:2.3},{id:'jump-module',type:'double-jump',x:28,y:0,label:'取得回弹二段跳'},{id:'energy-note',type:'note',x:16,y:0,label:'阅读：健康工作'}],
  enemies:[{id:'energy-shield',kind:'shield',x:14,y:0,min:10,max:19,hp:3},{id:'energy-sentry',kind:'sentry',x:24,y:2.2,min:24,max:24,hp:2}],
  chips:[{id:'e1',x:8,y:3.2},{id:'e2',x:25,y:3.2}],
  fact:'国际化健身中心是园区面向员工免费开放的运动空间。在这场训练中，用脉冲爪命中回收能量，再用能量发射远程脉冲或修复体力。完成试炼，获得回弹二段跳。'},
 archive:{name:'1楼电梯厅',subtitle:'600双鞋翻转墙 · 从起点继续向前',theme:'archive',width:32,map:[0,0],
  platforms:[p('floor',-2,34),p('shelf',8,15,2.2)],exits:{},
  items:[{id:'archive-back',type:'route',x:3,y:0,label:'返回水平连廊',room:'lab',toX:3,toY:5},{id:'archive-note',type:'note',x:11,y:2.2,label:'阅读：600 双鞋的起点'},{id:'archive-cache',type:'cache',x:26,y:0,label:'开启隐藏展柜',gear:'echo',requires:'archiveWall'}],
  wall:{id:'archiveWall',x:20,y:0,height:8,hp:3},
  enemies:[],chips:[{id:'v1',x:12,y:3.2},{id:'v2',x:28,y:1}],
  fact:'1楼电梯厅的600双鞋翻转墙讲述着创业起点，发光足迹墙串起步步向前的品牌故事。留意墙面的裂纹，用脉冲爪打开隐藏空间，找到展柜中的回响线圈。'},
 gallery:{name:'员工办公区',subtitle:'多品牌团队 · 动静相宜的灵感场',theme:'gallery',width:32,map:[3,1],trial:'galleryTrial',
  platforms:[p('floor',-2,34),p('l',5,11,2),p('m',14,20,4),p('r',24,30,2)],exits:{},
  items:[{id:'gallery-back',type:'route',x:3,y:0,label:'返回空中花园',room:'garden',toX:28,toY:6},{id:'gallery-cache',type:'cache',x:28,y:2,label:'开启共创奖励',gear:'guard',requires:'galleryTrial'},{id:'gallery-note',type:'note',x:17,y:4,label:'阅读：多品牌集群'}],
  enemies:[{id:'gallery-runner',x:11,y:0,min:8,max:19,hp:3},{id:'gallery-shield',kind:'shield',x:25,y:2,min:24,max:29,hp:3},{id:'gallery-sentry',kind:'sentry',x:17,y:4,min:17,max:17,hp:2}],
  chips:[{id:'b1',x:8,y:3},{id:'b2',x:18,y:5}],
  fact:'流线办公空间、木色旋转楼梯与绿植，让运动、交流和日常工作自然相融。安踏、斐乐、迪桑特、可隆等品牌团队在此集聚。完成混合训练挑战，取得共创奖励。'},
 arena:{name:'室内篮球场',subtitle:'专业赛事级 · 联动守卫试炼',theme:'arena',width:36,map:[3,0],
  platforms:[p('floor',-2,38),p('l',4,10,2.6),p('r',27,33,2.6)],
  exits:{left:{room:'garden',x:29,y:0}},
  items:[{id:'global-beacon',type:'finish',x:29,y:0,label:'点亮全球联动信标'}],enemies:[],chips:[],
  fact:'四层通高的室内篮球场，配以国际赛事级木地板、环形看台与光之穹顶，展现专业运动精神。在这里完成联动守卫试炼，点亮「扎根中国，赋能全球」的信标。'}
};
export const LINKS=[['core','lab'],['lab','hub'],['lab','garden'],['hub','atrium'],['atrium','garden'],['garden','arena'],['hub','garden'],['hub','energy'],['lab','archive'],['garden','gallery']];
export const TOTAL_CHIPS=Object.values(ROOMS).reduce((n,r)=>n+r.chips.length,0);
export const STEP=1/120, GRAVITY=28, JUMP=12.5, SPEED=7.5, RADIUS=.43;
export const SAVE_KEY='wanbu-metroid-v1';
