import {AdventureSession} from '../adventure/session.js';
import * as THREE from 'three';
import {RelayWorld,RelayCorgi,BASE_Y} from './world.js';
import {RelaySimulation} from './simulation.js';
import {BRANDS,CHAPTERS,SAVE,rhythm,onBeat} from './course.js';
import {AudioEngine} from '../audio.js';
import {SoundControls} from '../sound-controls.js';
const $=id=>document.getElementById(id);
class RelayGame{
 constructor(world,corgi){this.session=new AdventureSession('relay',SAVE);this.world=world;this.audio=new AudioEngine({scene:'relay'});this.sim=new RelaySimulation((type,data)=>this.event(type,data));const save=this.session.saved;this.sim.reset(save);this.keys=new Set();this.holds=new Map();this.joy=new THREE.Vector2();this.ui=this;this.active=false;this.paused=false;this.accumulator=0;this.saveTimer=0;this.toastTimer=0;this.finishTimer=0;this.shownFinish=false;this.player=new RelayCorgi(world,corgi);this.echoPlayer=new RelayCorgi(world,corgi,{echo:true});this.echoPlayer.visible=false;world.setupCourse(this.sim);world.resetCamera(this.sim);
  this.soundControls=new SoundControls(this.audio,this);const open=this.soundControls.open.bind(this.soundControls),close=this.soundControls.close.bind(this.soundControls);this.soundControls.open=()=>{this.clearInput();open();};this.soundControls.close=f=>{close(f);this.clearInput();};this.bind();this.syncAim();this.syncUI();$('start').disabled=false;$('start').textContent=this.sim.finished?'查看接力成果 →':save?'继续万步接力 →':'带球出发 →';$('loading').textContent='AD 移动 · 空格跳跃 · F 传球 · Q 吹哨';this.session.mount();
 }
 bind(){
  $('start').onclick=()=>this.start();$('menu').onclick=()=>this.pause();$('hint').onclick=()=>this.hint();$('close-dialog').onclick=()=>this.closeDialog();$('dialog').addEventListener('cancel',e=>{e.preventDefault();this.closeDialog();});
  for(const id of['pass','whistle','echo'])$(id).onclick=()=>this.action(id);
  $('angle').oninput=e=>{this.sim.angle=Number(e.target.value);this.syncAim();};$('power').oninput=e=>{this.sim.power=Number(e.target.value);this.syncAim();};$('aim-direction').onclick=()=>{this.sim.aimDir*=-1;this.syncAim();};
  for(const b of document.querySelectorAll('[data-hold]')){b.addEventListener('pointerdown',e=>{if(!this.playing)return;e.preventDefault();b.setPointerCapture(e.pointerId);this.holds.set(e.pointerId,b.dataset.hold);if(b.dataset.hold==='jump')this.sim.jump();this.audio.start();});const end=e=>this.holds.delete(e.pointerId);for(const event of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,end);}
  addEventListener('keydown',e=>{if(e.code==='Escape'){e.preventDefault();if(this.soundControls.opened)this.soundControls.close();else if($('dialog').open)this.closeDialog();else this.pause();return;}if(!this.playing||(['INPUT','TEXTAREA'].includes(e.target.tagName)&&e.target.type!=='range'))return;if(e.target.type==='range'&&e.code.startsWith('Arrow'))return;if(['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(e.repeat)return;if(e.code==='Space')this.sim.jump();if(e.code.startsWith('Shift'))this.sim.dash();if(e.code==='KeyF')this.action('pass');if(e.code==='KeyQ')this.action('whistle');if(e.code==='KeyE')this.action('echo');});
  addEventListener('keyup',e=>this.keys.delete(e.code));addEventListener('blur',()=>{this.clearInput();if(this.active&&!this.paused)this.pause(true);});document.addEventListener('visibilitychange',()=>{this.clearInput();if(document.hidden)this.save();});addEventListener('pagehide',()=>this.save());this.world.canvas.addEventListener('pointerdown',()=>this.world.canvas.focus());
 }
 get playing(){return this.session.valid()&&this.active&&!this.paused&&!this.sim.finished&&!document.hidden;}
 clearInput(){this.keys.clear();this.holds.clear();this.joy.set(0,0);this.accumulator=0;}
 start(){if(!this.session.valid())return;this.active=true;$('intro').hidden=true;$('play-hud').hidden=false;$('objective').hidden=false;this.world.canvas.focus();this.audio.start();this.audio.setChapter(this.sim.stage);if(this.sim.finished)this.finish();else this.toast(CHAPTERS[this.sim.stage].news,6);}
 action(id){if(!this.playing)return;this.audio.start();if(id==='pass')this.sim.playerThrow();if(id==='whistle'){this.audio.cue('whistle');this.sim.whistle();}if(id==='echo')this.sim.recordEcho();this.world.canvas.focus();}
 event(type,data){
  if(type==='notice')this.toast(data.text,4.5);
  if(['jump','land','throw','bounce','catch'].includes(type))this.audio.cue(type);
  if(type==='dash')this.audio.dash();
  if(type==='catch'){const h=this.sim.holder(data.owner);this.world.burst(h.x,h.y,0x9cfaff,8);if(data.owner!=='player')this.toast(`${data.owner} 接住了！${this.sim.stage===2?'吹哨，发起下一次助攻。':'按 Q 吹哨，让伙伴出发。'}`,4);this.save();}
  if(type==='echo'){this.audio.echo(true);this.world.burst(41,0);this.toast('回声已留在圆盘上。去阶梯和伙伴会合！',4);}
  if(type==='ring'){this.audio.collect();this.toast('精准穿环！收集到一枚联动光环。',3);}
  if(type==='recover'||type==='fall'){this.audio.fail();this.toast(data.text||'小步回到本段起点，接力进度仍然保留。',4);}
  if(type==='checkpoint'){this.world.resetCamera(this.sim);this.syncAim();this.clearInput();this.audio.success();this.audio.setChapter(this.sim.stage);this.toast(`${data.retry?'重新挑战':'接力进入'} · ${CHAPTERS[this.sim.stage].title}`,4);this.save();}
  if(type==='head-ready')this.toast(data.good?'就是现在，小步起跳！':'这一拍偏早了，试着等节奏变青。',2);
  if(type==='finish'){this.audio.complete();this.world.burst(130,3.4,0xffd58d,32);this.clearInput();this.finishTimer=1.9;this.save();try{if(!this.session.campus)localStorage.setItem('wanbu-reward-cocreation-core','unlocked');}catch{}this.toast('球进了！全楼联动，接力完成。',3);}
 }
 syncAim(){$('angle').value=this.sim.angle;$('power').value=this.sim.power;$('angle-value').textContent=this.sim.angle+'°';$('power-value').textContent=this.sim.power;$('aim-direction').textContent=this.sim.aimDir>0?'向右 ↗':'↖ 向左';}
 syncUI(){const s=this.sim;const holding=s.ball.owner==='player';$('team-count').textContent=s.visited.size+' / 4';const sig=[...s.visited].join();if(this.teamSig!==sig){$('team-dots').innerHTML=BRANDS.map(id=>`<em class="${s.visited.has(id)?'done':''}" title="${id}" aria-label="${id}${s.visited.has(id)?'已接力':'待接力'}">${id}</em>`).join('');this.teamSig=sig;}
  $('stage-name').textContent=`0${s.stage+1} · ${CHAPTERS[s.stage].title}`;let task;
  if(s.stage===0)task=s.phase==='first-pass'?'到 6 米发球圈，将球传给上层伙伴':s.phase==='first-done'?'接应成功！带球穿过右侧连廊':'吹哨让伙伴出发，到 29 米处接回球';
  if(s.stage===1)task=s.phase==='lift-pass'?'把球传给前方 FILA 伙伴':!s.echo?'到 41 米圆盘按 E，留下回声':s.phase==='lift-done'?'带球从上层右侧离开，进入篮球场':s.npcs[1].x<61.8?'吹哨出发，沿阶梯跃上移动接应台':'站上青色移动台，吹哨接球';
  if(s.stage===2)task=s.phase==='shot-ready'?'到 118 米，节奏变青时按 F 跃起顶球':s.visited.has('DESCENTE')&&s.visited.has('KOLON')?'到 118 米，吹哨接回最后一棒':s.ball.owner==='player'?'到 88 米传给 DESCENTE；也可以先传 KOLON':'吹哨，让两位伙伴完成助攻';
  if(s.finished)task='全楼联动，接力完成。';$('task').textContent=task;
  $('ball-state').textContent=holding?'小步持球':s.ball.owner==='hoop'?'接力完成':s.ball.owner?`${s.ball.owner} 持球`:'联动球飞行中';$('pass').disabled=!holding||s.finished;$('echo').disabled=s.stage!==1||s.finished;$('whistle').disabled=$('jump').disabled=s.finished;$('angle').disabled=$('power').disabled=!holding;$('pass-label').textContent=s.stage===2&&s.phase==='shot-ready'&&s.x>=116&&s.x<=123?'顶球':'传球';$('position').textContent=`${Math.round(s.x)} m · 穿环 ${s.rings.size}/3`;
  document.querySelectorAll('[data-stage]').forEach(el=>{el.classList.toggle('current',Number(el.dataset.stage)===s.stage);el.classList.toggle('done',Number(el.dataset.stage)<s.stage||s.finished);});
  const beat=s.stage===2&&s.phase==='shot-ready'&&s.x>=116&&s.x<=123&&!s.finished;$('aim-panel').hidden=beat;$('beat').hidden=!beat;$('beat').classList.toggle('good',onBeat(s.time));$('beat-label').textContent=onBeat(s.time)?'现在！跃起顶球':'跟上这一拍';$('beat-dot').style.left=`${rhythm(s.time)*98}%`;
 }
 toast(text,seconds=4){$('toast').textContent=text;$('toast').classList.add('visible');this.toastTimer=seconds;}
 save(){this.session.save(this.sim.snapshot());}
 openDialog(html){this.clearInput();this.paused=true;$('dialog-body').innerHTML=html;this.session.decorate($('dialog-body'),this.sim.finished);if(!$('dialog').open)$('dialog').showModal();this.save();}
 closeDialog(){$('dialog').close();this.paused=false;this.clearInput();this.world.canvas.focus();}
 pause(force=false){if(!this.active)return;if($('dialog').open&&!force){this.closeDialog();return;}this.openDialog(`<h2>接力，歇一会。</h2><p>检查点已保存。AD / 方向键移动，空格跳跃，Shift 冲刺。调整角度和力度，F 传球；Q 指挥伙伴，E 在中庭留下回声。</p><button class="primary" id="resume">继续接力 →</button><button class="secondary" id="retry-stage">重试当前一段</button><button class="secondary" id="dof-toggle">${this.world.pixelLabel} · 切换</button><button class="secondary" id="restart">从头挑战本章</button><a class="secondary" href="./lab.html">返回 ANTA 科技密室</a><a class="secondary" href="./index.html">返回运动闯关</a>`);$('resume').onclick=()=>this.closeDialog();$('retry-stage').onclick=()=>{this.sim.restartStage();this.shownFinish=false;this.closeDialog();};$('dof-toggle').onclick=()=>{$('dof-toggle').textContent=this.world.cyclePixelMode()+' · 切换';};$('restart').onclick=()=>this.confirmRestart();}
 confirmRestart(){this.openDialog('<h2>重新开始接力？</h2><p>本章的当前进度将重新开始。已获得的共创核心、运动关和科技密室进度会保留。</p><button class="primary" id="confirm-restart">重新开赛 →</button><button class="secondary" id="cancel-restart">保留进度</button>');$('cancel-restart').onclick=()=>this.pause(true);$('confirm-restart').onclick=()=>{this.sim.reset();this.shownFinish=false;this.finishTimer=0;this.world.resetCamera(this.sim);this.syncAim();this.save();this.closeDialog();};}
 hint(){const c=CHAPTERS[this.sim.stage];this.openDialog(`<h2>${c.title}</h2><p>${c.hint}</p><p>沿发光轨迹瞄准，球接近伙伴或小步就会自动接住。传偏会自动回到上一位持球者。吹哨可让移动中的伙伴停下或继续。</p><p class="source">伙伴的提示：${c.news}<br>ANTA、FILA、DESCENTE、KOLON 四位伙伴已在路线中等你。回声项圈延续自第二关；直接进入本关也可使用中庭的体验装置。接力比赛与全息设备为虚拟玩法。</p><button class="primary" id="got-it">继续接力 →</button>`);$('got-it').onclick=()=>this.closeDialog();}
 finish(){if(this.shownFinish)return;this.shownFinish=true;const s=this.sim,seconds=Math.round(s.time),duration=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;this.openDialog(`<div class="reward" aria-hidden="true">◎</div><h2>一颗球，让全楼联动。</h2><p>连廊妙传、中庭接应、午间决胜球，全线完成。四位伙伴的助攻，被小步送进了最后一球。</p><div class="result-stats"><span><b>${duration}</b>接力用时</span><span><b>${s.bestCombo}</b>最高连击</span><span><b>${s.rings.size} / 3</b>精准穿环</span></div><p><b>获得奖励：共创核心</b><br>奖励和通关记录已保存在本机。</p><button class="primary" id="replay">再来一次 →</button><button class="secondary" id="view-court">回到球场</button><a class="secondary" href="./lab.html">重访 ANTA 科技密室</a><p class="source">从水平连廊到垂直中庭，从团队协作到员工运动空间，把「万步联动」变成一次共同完成的接力。</p>`);$('replay').onclick=()=>this.confirmRestart();$('view-court').onclick=()=>this.closeDialog();}
 update(dt){this.audio.setState(this.active&&this.paused&&!this.soundControls.opened,document.hidden);const s=this.sim;if(this.playing){this.accumulator+=Math.min(dt,.06);const held=[...this.holds.values()],left=this.keys.has('KeyA')||this.keys.has('ArrowLeft')||held.includes('left'),right=this.keys.has('KeyD')||this.keys.has('ArrowRight')||held.includes('right');const input={axis:Number(right)-Number(left),jumpHeld:this.keys.has('Space')||held.includes('jump')};while(this.accumulator>=1/120){s.step(1/120,input);this.accumulator-=1/120;if(this.paused||s.finished)break;}if(s.grounded&&Math.abs(s.vx)>.5)this.audio.step(s.time,false,!!s.dashTime);this.saveTimer+=dt;if(this.saveTimer>2){this.saveTimer=0;this.save();}}
  if(this.finishTimer>0){this.finishTimer-=dt;if(this.finishTimer<=0)this.finish();}if(this.toastTimer>0){this.toastTimer-=dt;if(this.toastTimer<=0)$('toast').classList.remove('visible');}
  this.player.animate(this.paused?0:dt,s);this.echoPlayer.visible=!!s.echo;if(s.echo)this.echoPlayer.animate(this.paused?0:dt,{x:41,y:0,facing:1,grounded:true,vx:0,vy:0});this.world.update(this.paused?0:dt,s);this.syncUI();this.world.render();
 }
}
async function boot(){try{const world=new RelayWorld($('world'));const {corgi}=await world.load((progress,label)=>{$('loading').textContent=`${label} · ${Math.round(progress*100)}%`;});const game=new RelayGame(world,corgi);window.relayGame=game;let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.1);last=now;if(!document.hidden)game.update(dt);}requestAnimationFrame(frame);}catch(error){console.error(error);$('load-error').hidden=false;$('error-message').textContent='请确认本地服务仍在运行，然后重新载入。'+(error.message||'');}}
boot();
